#!/usr/bin/env bash
# ─────────────────────────────────────────
#  WETG Launcher
#  Usage:
#    wetg run mybot.wetg
#    wetg new mybot.wetg
#    wetg help
# ─────────────────────────────────────────

WETG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WETG_PY="$WETG_DIR/wetg.py"
VERSION="7"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

print_logo() {
    echo -e "${CYAN}${BOLD}"
    echo "  ██╗    ██╗███████╗████████╗ ██████╗ "
    echo "  ██║    ██║██╔════╝╚══██╔══╝██╔════╝ "
    echo "  ██║ █╗ ██║█████╗     ██║   ██║  ███╗"
    echo "  ██║███╗██║██╔══╝     ██║   ██║   ██║"
    echo "  ╚███╔███╔╝███████╗   ██║   ╚██████╔╝"
    echo "   ╚══╝╚══╝ ╚══════╝   ╚═╝    ╚═════╝ "
    echo -e "${NC}${YELLOW}  v${VERSION} Super Weox — One-File Telegram Bot Engine${NC}"
    echo ""
}

print_help() {
    print_logo
    echo -e "${BOLD}Usage:${NC}"
    echo "  wetg run <file.wetg>     Run a WETG bot"
    echo "  wetg new <file.wetg>     Create a new bot from template"
    echo "  wetg check <file.wetg>   Validate/parse a .wetg file"
    echo "  wetg version             Show version"
    echo "  wetg help                Show this help"
    echo ""
    echo -e "${BOLD}Examples:${NC}"
    echo "  wetg run mybot.wetg"
    echo "  wetg new mybot.wetg && wetg run mybot.wetg"
    echo ""
}

cmd_run() {
    if [ -z "$1" ]; then
        echo -e "${RED}❌ No file specified. Usage: wetg run mybot.wetg${NC}"
        exit 1
    fi
    if [ ! -f "$1" ]; then
        echo -e "${RED}❌ File not found: $1${NC}"
        exit 1
    fi
    echo -e "${GREEN}🔥 WETG v${VERSION} Super Weox${NC}"
    python3 "$WETG_PY" run "$1"
}

cmd_new() {
    if [ -z "$1" ]; then
        echo -e "${RED}❌ Specify a filename. Usage: wetg new mybot.wetg${NC}"
        exit 1
    fi
    if [ -f "$1" ]; then
        echo -e "${YELLOW}⚠️  File already exists: $1${NC}"
        exit 1
    fi
    cat > "$1" <<'EOF'
# ─────────────────────────────────────────
# WETG Bot — generated by `wetg new`
# Replace YOUR_TOKEN with your bot token
# from @BotFather on Telegram
# ─────────────────────────────────────────

bot "YOUR_TOKEN_HERE"

set greeting=Hello

on /start
    send "👋 Hi {user.name}! I'm {bot.username}."
    send "Type /help to see what I can do."

on /help
    send "Commands:\n/start — greet\n/echo — repeat your next message\n/ping — pong!"

on /ping
    send "🏓 Pong!"

on /echo
    ask "What should I echo back?"

on usermsg
    send "You said: {usermsg}"
EOF
    echo -e "${GREEN}✅ Created: $1${NC}"
    echo -e "   Edit the file and add your bot token, then run:"
    echo -e "   ${CYAN}wetg run $1${NC}"
}

cmd_check() {
    if [ -z "$1" ]; then
        echo -e "${RED}❌ No file specified.${NC}"
        exit 1
    fi
    if [ ! -f "$1" ]; then
        echo -e "${RED}❌ File not found: $1${NC}"
        exit 1
    fi
    echo -e "${CYAN}🔍 Checking $1 ...${NC}"
    python3 - "$1" <<'PYEOF'
import sys
sys.path.insert(0, __import__('os').path.dirname(sys.argv[0]))

# Minimal parse check without importing telegram
class Wetg:
    def __init__(self, code):
        self.code = code.splitlines()
        self.token = None
        self.commands = []
        self.functions = []
        self.variables = []

    def parse(self):
        for line in self.code:
            s = line.strip()
            if s.startswith("bot "): self.token = True
            elif s.startswith("on "): self.commands.append(s[3:])
            elif s.startswith("function "): self.functions.append(s[9:])
            elif s.startswith("set "):
                try:
                    k,v = s[4:].split("=",1)
                    self.variables.append(k.strip())
                except: pass

with open(sys.argv[1], encoding="utf-8") as f:
    code = f.read()

w = Wetg(code)
w.parse()
print(f"  Token defined : {'✅ Yes' if w.token else '❌ No — add: bot \"TOKEN\"'}")
print(f"  Commands      : {len(w.commands)} → {', '.join(w.commands) if w.commands else 'none'}")
print(f"  Functions     : {len(w.functions)} → {', '.join(w.functions) if w.functions else 'none'}")
print(f"  Variables     : {len(w.variables)} → {', '.join(w.variables) if w.variables else 'none'}")
PYEOF
}

# ─── Entry point ───
case "$1" in
    run)     cmd_run "$2" ;;
    new)     cmd_new "$2" ;;
    check)   cmd_check "$2" ;;
    version) echo "WETG v${VERSION} Super Weox" ;;
    help|"") print_help ;;
    *.wetg)  cmd_run "$1" ;;          # shortcut: wetg mybot.wetg
    *)
        echo -e "${RED}❌ Unknown command: $1${NC}"
        echo "Run 'wetg help' for usage."
        exit 1
        ;;
esac
